spring.application.name=cineverse-backend

server.port=${PORT:8080}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://cineverse-by-rohit.vercel.app}

admin.emails=${ADMIN_EMAILS:admin@cineverse.com}